### ISSUE TITLE
Support for Basketball

### ISSUE THREAD

**Issue by Bart274** [mmmmmtasty/SportScanner#1]
Hi,

Could you please add support for Basketball?
I want to add my NBA Games to my Plex installation.

**Comment by Bart274** [comment]
I have added support for Basketball using this:

seasons = { "Soccer" : { "split_date" : [7,1], "season_format" : "xxyy"},
            "Ice Hockey" : { "split_date" : [7,1], "season_format" : "xxyy"},
            "Motorsport" : { "season_format" : "yyyy"},
            "Baseball" : { "season_format" : "yyyy"},
			"Basketball" : { "split_date" : [7,1], "season_format" : "xxyy"}}

**Comment by mmmmmtasty** [comment]
Perfect, pull request merged.
