### ISSUE TITLE
parser for NBA

### ISSUE THREAD

**Issue by Bart274** [mmmmmtasty/SportScanner#10]
Hi,

Would you able to write a parses for NBA games similar to the one you wrote for NHL? :)

**Comment by mmmmmtasty** [comment]
I don't know exactly what you mean? The scanner should work for NBA and NHL and most other sports already. What is missing that you would like to work?

MmmmmTasty

**Comment by Bart274** [comment]
I meant a file like Parse-NHL.ps1 but then Parse-NBA.ps1 to automatically update the NBA games on sportsdb :)

**Comment by zag2me** [comment]
As long as it follows the csv format output, you can write any kind of script you wish. I'll implement it if it works.

**Comment by mmmmmtasty** [comment]
This has been done - it's up to zag to fix a couple of inconsistencies in thesportsdb data and confirm that what I've provided does work properly but then he should be able to go live with that too.

**Comment by Bart274** [comment]
Alright! Thanks a lot for this! :+1: This would help me a lot! :)
