### ISSUE TITLE
Initial Cover Art/Naming?

### ISSUE THREAD

**Issue by Superduper09** [mmmmmtasty/SportScanner#13]
Hi
I am having an issue with getting the naming/art working for Motorsport/Formula 1 races. 

I have all of 2015 Season currently in:
Sports>Formula 1 2015>"F1.2015.03.15.Australia 2015 SkyF1 Race Session.720p50.mp4" 
and the folder in Plex gets named 
Sports > "Formula 1 2015:F1" > Season 2015 > Australia 2015 SkyF1 Race Session

However there is no poster art for Formula 1 section (within the Sports library) -- and even when I add it, on rescan it gets deleted (same with any custom renaming).

I previously had it Sports > Motorsport > Formula 1 > Season 2015 > "F1.2015.03.15.Australia 2015 SkyF1 Race Session.720p50.mp4"  but that made the Plex title Motorsport/Formula1/Season 2015 -- so it didn't look good in Plex, and as noted when manually changed/locked it got reset after rescanning. 

Just a small nitpick...not sure what I am doing wrong/if there is a fix...otherwise very happy it is working so far/scanning in Plex!!

Thanks!

**Comment by zag2me** [comment]
Here is the corresponding event on TheSportsDB

http://www.thesportsdb.com/event/447358

Seems to have a poster already. 

You can see an example filename at the bottom of the page.

**Comment by Superduper09** [comment]
Thanks I can try tinkering with it later tonight, it picked up the episode
name format so I figured my name format was working - but none of the
posters/images would load in Plex.
I manually updated it using the links to the images on sportsdb, but as
noted it would get reset after scanning...

**Comment by mmmmmtasty** [comment]
Hi Superduper09

Your original layout is the way it should be: Sports/Motorsport/Formula 1/Season 2015/<event>. Could you show me what you mean was breaking - perhaps a screenshot?

The naming of your files is not like any that I've used or tested with so that might be the issue. Could you give me a log file that shows this file being scanned? The scanner should be able to match events when there is only one event on that particular date even if the title is a bit screwed up.

Thanks

MmmmmTasty

**Comment by Superduper09** [comment]
Hi,

Sure let's see, I basically am having trouble with getting the art to load/everything to scan correctly.

So I made the folder as I had it originally, and put 1 file in properly named, using the file example "Formula 1 2015-03-15 Australian Grand Prix.mp4" -- however this did not get picked up by the scan. I then changed it to how I had it "F1.2015.03.15.Australia 2015 SkyF1 Race Session.720p50.mp4", and it did get picked up. 

Here are the logs of the scans, let me know if you need anything else:
[F1 renamed not picked up.txt](https://github.com/mmmmmtasty/SportScanner/files/141895/F1.renamed.not.picked.up.txt)
[F1 renamed picked up.txt](https://github.com/mmmmmtasty/SportScanner/files/141896/F1.renamed.picked.up.txt)
[Sportscanner Log.txt](https://github.com/mmmmmtasty/SportScanner/files/141897/Sportscanner.Log.txt)

Here is what my Plex on Sports with the 2 F1 folders looks like after (note the cover art on the left side is what I am trying to do, just not manually)

![image](https://cloud.githubusercontent.com/assets/17391966/13240953/bfc12890-d99b-11e5-8a75-41409970a6de.png)

If you notice the Motorsport/Formula 1/Season 2015 folder on the right doesn't show as "Formula 1", and just the folder name (doesn't look good). The other folder is titled "Formula 1 2015: F1. Both go to the Season view after clicking:

![image](https://cloud.githubusercontent.com/assets/17391966/13241156/6db141a0-d99d-11e5-8273-6871fe1eca65.png)
![image](https://cloud.githubusercontent.com/assets/17391966/13241159/74c371e8-d99d-11e5-91aa-eba9f9b6d7f7.png)

and after clicking into Season on both
:
![image](https://cloud.githubusercontent.com/assets/17391966/13241169/836406e0-d99d-11e5-8350-2ce63dfc4286.png)
![image](https://cloud.githubusercontent.com/assets/17391966/13241173/8a69c8b2-d99d-11e5-93b7-89260a7c1cb5.png)

Note, my content in the "Formula 1 2015: F1" is not in a Season 2015 sub folder (Sports\Formula 1 2015\xxx.mp4), so I am assuming it is getting picked up properly somewhere?

Now for what was breaking... I was able to reproduce it when I changed the Motorsport\Formula 1 category on plex to Formula 1:
![image](https://cloud.githubusercontent.com/assets/17391966/13241289/6fdaf8e4-d99e-11e5-95a9-70c9c2ce3699.png)

I then added 23 files to that folder and rescanned, and it "broke" by renaming the category back (if I added poster art I assume it would have also went back to default/no art -- the art/titles are what I meant by what was breaking)
![image](https://cloud.githubusercontent.com/assets/17391966/13241356/f88c5bf6-d99e-11e5-9631-92618835489a.png)

[Scan after F1 folder rename.txt](https://github.com/mmmmmtasty/SportScanner/files/141914/Scan.after.F1.folder.rename.txt)
[Updated sports scanner log.txt](https://github.com/mmmmmtasty/SportScanner/files/141912/Updated.sports.scanner.log.txt)


So for now I have the files somewhat able to be scanned --it picks up the episode naming as 315xxxx, from what I understand it is MDD then 4 random numbers-- So the March 15 race in Australia is 315xxxx, March 29 race in Malaysia is 329xxxx etc... it just seems like it should be grabbing some art too?

Thanks!

**Comment by mmmmmtasty** [comment]
Are you running Windows?

I can see that the scanner is picking up the show name as "Motorsport\Formula 1\Season 2015" which is obviously wrong and why it looks so strange for you.

I have created the following and it matches the show and season properly (it doesn't get the episode named perfectly but I'm looking at that):

"P:\SportsTest\Motorsport\Formula 1\Season 2015\F1.2015.03.15.Australia 2015 SkyF1 Race Session.720p50.mp4"

Are you running the latest version of the Scanner (more important than the metadata agent part)? Please make sure you have the latest version, restart your PMS and then create a new section with the SportScanner agent and scanner and then send me the log file.

Apologies but I can't replicate the behaviour you are seeing right now.

Thanks

**Comment by mmmmmtasty** [comment]
Please make sure you have the latest copy of the scanner scripts, make sure the sportsdb is up and working, then create a brand new SportsTest section pointing at your sports directories. Make sure the naming is in this form:

/Volumes/HTPC 03/Sport/Motorsport/MotoGP/Season 2015/MotoGP.2015.06.27.Motul.TT.Assen.720p.HDTV.mkv

Then when you have created the section and the scanning etc is completed please send me the following three log files:

~/Library/Logs/Plex Media Server/Plex Media Server.log
~/Library/Logs/Plex Media Server/Plex Media Scanner.log
~/Library/Logs/Plex Media Server/PMS Plugin Logs/com.plexapp.agents.sportscanner.log

**Comment by mmmmmtasty** [comment]
v0.2 released, check out the readme, download the latest release, recreate your library and let me know how it goes.

**Comment by Superduper09** [comment]
Thanks! Interesting...it is putting them in as "Special", but seems to be formatted better, pics below. Isn't picking up art still though. 

After the update I tried renaming one of the files to the format from sportsdb but didn't change anything either (Formula 1 2016-03-20 Australian Grand Prix.mp4 vs F1.2016.03.20.Australia 2016 Race Session.1080p50.mp4)

![image](https://cloud.githubusercontent.com/assets/17391966/14234375/d7b5f3ac-f996-11e5-839f-62fda879365a.png)
![image](https://cloud.githubusercontent.com/assets/17391966/14234377/defda312-f996-11e5-86c0-983cc6ac17ca.png)
![image](https://cloud.githubusercontent.com/assets/17391966/14234380/e4fd37e6-f996-11e5-93ac-1e7c90871f31.png)
![image](https://cloud.githubusercontent.com/assets/17391966/14234382/ea49b2ec-f996-11e5-872c-5f1798eea6d6.png)

Here are the logs:
[com.plexapp.agents.sportscanner.txt](https://github.com/mmmmmtasty/SportScanner/files/201514/com.plexapp.agents.sportscanner.txt)
[Plex Media Scanner.txt](https://github.com/mmmmmtasty/SportScanner/files/201515/Plex.Media.Scanner.txt)
[Plex Media Server.txt](https://github.com/mmmmmtasty/SportScanner/files/201516/Plex.Media.Server.txt)

**Comment by mmmmmtasty** [comment]
Hiya, I should have mentioned, check out the readme and you will see that the folder structure requirement has changed a bit. You have this (which is what I used to make you have):

Z:\Sports\Motorsport\Formula 1\Season 2016

It must now be this:

Z:\Sports\Formula 1\Season 2016

Sorry for that, the original folder structure was a bad design decision by me, the new one is much more sensible and should work more reliably.

Thanks

**Comment by Superduper09** [comment]
Ah got it, thank you! It is working now :)

My file format structure may need some work now though...is there a way to somehow sort or name format for having a pre race/race/post race?
![image](https://cloud.githubusercontent.com/assets/17391966/14234850/775a1946-f9a2-11e5-8250-d4b1caa26e59.png)

**Comment by mmmmmtasty** [comment]
There isn't unfortunately. How do you think it should look. Different episodes or merging the three videos into one episode? Please open a feature request with some details of what naming schemes you have and how you would like it to work and I'll see what is possible. Thanks, glad to hear it's working now.
