### ISSUE TITLE
Unmatched in Plex and missing description

### ISSUE THREAD

**Issue by robflate** [mmmmmtasty/SportScanner#14]
I'm getting "Unmatched" added to the start of some episodes in Plex. Also, the description (if one exists) doesn't get added to each episode in Plex. E.g.

This works. Thumbnail is added. No description added;
`MotoGP.2015.05.17.Monster.Energy.Grand.Prix.de.France.720p.HDTV.mkv`
Event: http://www.thesportsdb.com/event/448719

This doesn't work. Unmatched is added to episode name in Plex. No thumbnail. No description;
`MotoGP.2015.06.27.Motul.TT.Assen.720p.HDTV.mkv`
Event: http://www.thesportsdb.com/event/448722

Any advice appreciated. Thanks.

**Comment by mmmmmtasty** [comment]
I will check this out tonight.

**Comment by mmmmmtasty** [comment]
Could you let me know what folder structure you have? I just did the following with the latest version of SportScanner and it all worked just fine:

"P:\SportsTest\Motorsport\MotoGP\Season 2015\MotoGP.2015.05.17.Monster.Energy.Grand.Prix.de.France.720p.HDTV.mkv"

and 

"P:\SportsTest\Motorsport\MotoGP\Season 2015\MotoGP.2015.06.27.Motul.TT.Assen.720p.HDTV.mkv"

Both have descriptions and are properly matched. Could it be that they weren't matched when they were first added and now refuse to match properly? There is a problem where items don't seem to update in the library when the metadata source gets updated.

Please let me know the folder structure you are using and if you are still having trouble please attach the scanner logs.

Thanks

**Comment by robflate** [comment]
My folder structure was;

`/Volumes/HTPC\ 03/Media/Sport/Motorsport/MotoGP.2015.05.17.Monster.Energy.Grand.Prix.de.France.720p.HDTV.mkv`

and

`/Volumes/HTPC\ 03/Media/Sport/Motorsport/MotoGP.2015.06.27.Motul.TT.Assen.720p.HDTV.mkv`

I just set it up using your folder structure and it seems worse. Missing description/art on main MotoGP entry and strange naming. See attached images and log file.

![plex 1](https://cloud.githubusercontent.com/assets/4172375/14031544/3235c29c-f205-11e5-8d81-ea09a715ad00.jpg)
![plex 2](https://cloud.githubusercontent.com/assets/4172375/14031548/356bd80c-f205-11e5-9cfb-bedfdd4521cf.jpg)
[Plex Media Scanner.txt](https://github.com/mmmmmtasty/SportScanner/files/188702/Plex.Media.Scanner.txt)

**Comment by mmmmmtasty** [comment]
I'm guessing from those paths that you are running your server on a Mac?
All my testing has been with a windows server, I will test this too.

**Comment by robflate** [comment]
Yes, I'm on a mac. Sorry, didn't think to say.

**Comment by mmmmmtasty** [comment]
Hi robflate. thesportsdb.com seems to be down right now which is not helping with my troubleshooting :(

I have tried replicating the issues in your screenshot running PMS on a Mac and I cannot currently do so.

Please make sure you have the latest copy of the scanner scripts, make sure the sportsdb is up and working, then create a brand new SportsTest section pointing at your sports directories. Make sure the naming is in this form:

/Volumes/HTPC 03/Sport/Motorsport/MotoGP/Season 2015/MotoGP.2015.06.27.Motul.TT.Assen.720p.HDTV.mkv

Then when you have created the section and the scanning etc is completed please send me the following three log files:

~/Library/Logs/Plex Media Server/Plex Media Server.log
~/Library/Logs/Plex Media Server/Plex Media Scanner.log
~/Library/Logs/Plex Media Server/PMS Plugin Logs/com.plexapp.agents.sportscanner.log

**Comment by mmmmmtasty** [comment]
I just realised - you are using a very out of date version of the scanner - the part that adds "Umatched" to episodes was removed in October last year. Please use the latest version.

**Comment by robflate** [comment]
So sorry about that. I must have followed the link in the readme to the latest release and got that. I've now downloaded the master and it works.

However, I have another problem. I just added an F1 race and it's being added to the MotoGP section in Plex. Here's my folder structure

**MotoGP**
/Volumes/HTPC 03/Sport/Motorsport/MotoGP/Season 2015/MotoGP.2015.06.27.Motul.TT.Assen.720p.HDTV.mkv

**F1**
/Volumes/HTPC 03/Sport/Motorsport/F1/Season 2015/F1.2016.03.20.Australian.Grand.Prix.720p.HDTV.mkv

I also tried "Formula 1", "Formula.1" and "Formula 1" but they all ended up in the MotoGP section.

[com.plexapp.agents.sportscanner.txt](https://github.com/mmmmmtasty/SportScanner/files/192352/com.plexapp.agents.sportscanner.txt)
[Plex Media Scanner.txt](https://github.com/mmmmmtasty/SportScanner/files/192353/Plex.Media.Scanner.txt)
[Plex Media Server.txt](https://github.com/mmmmmtasty/SportScanner/files/192354/Plex.Media.Server.txt)

**Comment by mmmmmtasty** [comment]
Laaaaame - I've worked this one out. The problem is that although my scanner knows how to read the folder structure that I have told you to use, at some point I have to hand stuff back to Plex and it then overrides some of my decisions. This does not happen on Windows, only OSX which is why I have not found it earlier.

The problem is that there is one too many levels in the directory structure. Plex expects:

/Volumes/Multimedia/Sport/Formula 1/Season 2015

and I make people make:

/Volumes/Multimedia/Sport/Motorsport/Formula 1/Season 2015 

Annoyingly I think I will have to change the way the scanner works to accommodate this....while trying to maintain backwards compatibility for the existing recommended folder structure.

**Comment by robflate** [comment]
Thanks for tracking the problem down. If I use the structure Plex expects, will it work or should I wait for a fix to the scanner?

**Comment by mmmmmtasty** [comment]
It won't work because my scanner will be confused. I've asked for another
API call from the sports dB which should help here so watch this space.

**Comment by zag2me** [comment]
API updated, let me know on forum if its correct ;)

**Comment by mmmmmtasty** [comment]
I've updated and pushed the latest scanner. I created release 0.2. Please read the readme (it has been updated), follow the advice for naming folders and let me know if there are still issues for you. I have tested this with success here but I made quite a few changes so I wouldn't be too surprised to see issues.

Feel free to re-open this if I haven't fixed this issue but please open another issue if you find anything that doesn't directly belong in this issue.

Thanks

MmmmmTasty
