### ISSUE TITLE
Update Powershell scripts NHL and NBA for 2016 season

### ISSUE THREAD

**Issue by zag2me** [mmmmmtasty/SportScanner#15]
I gave it a quick try but it didnt work for some reason, can you take a look on how to update for next season?

**Comment by zag2me** [comment]
ping @mmmmmtasty

**Comment by mmmmmtasty** [comment]
Hi zag, I just took a quick look and I can't really do this until the season starts as I don't have example data yet. I don't see any major reasons why they wouldn't work when the seasons start though. Have you seen some other issues?

**Comment by zag2me** [comment]
NHL confirmed working now :+1: although its missing the round number (but I think this was always the case).

I'll check NBA when the season starts next week.

**Comment by mmmmmtasty** [comment]
Awesome!
