### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by chickey** [mmmmmtasty/SportScanner#17]
I've just found this today and would love to get it working, i'm primarily wanting to use it for motoGP.

I'll be honest i'm not sure if i've got it installed correctly, i'm running it under ubuntu so have unpacked the files to the default folder of

/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/

i've moved the SportScanner.bundle file into the plug-ins directory.  It mentions to move the extracted scanners directory into the plex main folder, is this the whole achive minus the .bundle file or just the scanners dir which contains the series folder only?

Lastly it mentions to copy the SportsScanner.py into your newly created folder, sorry for being an idiot but which new folder?

Sorry as others seem to have managed ok but it's my first time dabbling with custom scanners/agents.

**Comment by mmmmmtasty** [comment]
Sorry, reading this my instructions are a bit unclear. Copy the "Scanners" folder into your main Plex folder. Copy the bundle into the Plug-Ins folder under your main Plex folder. 

That should be it!

**Comment by chickey** [comment]
Everyone else seems to have managed so i'll take the blame rather than your instructions.  I've created a new library and pointed it to my files which are stored at 
\\media\storage\sports\Motorsport

under this folder i've got a folder MotoGP and another Moto2, i initially had each file in a folder under there but on reading your structure i've created a folder called season 2016 and put my files in these folders but they don't appear to be appearing correctly, it's created a specials folder under the new library i created and placed the files there but without any other details if that makes sense.

I've named the files using the required standard such as 

motogp.2016.09.25.aragon.mkv

I've attached a few log files if it helps.

BTW really appreciate your help on this.

[Logs.zip](https://github.com/mmmmmtasty/SportScanner/files/562945/Logs.zip)
![capture](https://cloud.githubusercontent.com/assets/1386109/19873103/00daf2ea-9fb5-11e6-8a99-7aa43eb2fe9f.JPG)

**Comment by mmmmmtasty** [comment]
I think this is due to the naming of the files. Some of them are in formats
I haven't seen before and the rest in formats that I know don't work. Try
naming one of them in the recommended way and see of it gets picked up. If
you could send me a sample of each of the styles of naming I can maybe try
and add some different matching types but it would definitely be quicker
for you to rename your files.

**Comment by chickey** [comment]
sorry i'd only renamed a sample of the files for testing.  I thought the one i mentioned above was in the correct format so

MotoGP 2016.09.25 Aragon.mkv  

or for a Moto2 race

Moto2 2016-10-30 Malaysia Motorcycle Grand Prix.mkv

I'm happy to rename the files to suit your style, i need to put something in place to format the names so they have the date in them anyway.

I've attached a screenshot as how the actual files appear rather than just the library as i showed previously, i've renamed all files with a date as per the convention.

![capture](https://cloud.githubusercontent.com/assets/1386109/19873867/5a360ed4-9fb9-11e6-84b8-a5b12653df51.JPG)
