### ISSUE TITLE
NBA powershell broken

### ISSUE THREAD

**Issue by zag2me** [mmmmmtasty/SportScanner#18]
Now that the season has restarted, looks like there is an error with the NBA.com API.

PS C:\> .\nba.ps1
Invoke-WebRequest : Access Denied
You don't have permission to access "http://stats.nba.com/stats/scoreboard/?" on this server.
Reference #18.1e6f5668.1478959690.724c4e8
At C:\nba.ps1:38 char:17

**Comment by zag2me** [comment]
Some info and possible fix here, something about setting the referal header. I wonder if thats even possible in Powershell?

https://www.reddit.com/r/nba/comments/3k91g5/finally_some_documentation_for_the_statsnbacom_api/

**Comment by mmmmmtasty** [comment]
Fixed, pull the latest version.

**Comment by zag2me** [comment]
Getting  a new error now

Invoke-WebRequest : The 'Referer' header must be modified using the appropriate property or method.
Parameter name: name
At C:\Parse-NBA.ps1:15 char:11
+ $teams = (Invoke-WebRequest $teamUrl -WebSession $websession | ConvertFrom-Json) ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by mmmmmtasty** [comment]
What version of powershell are you using? (type $psversiontable in your
powershell console) it works on mine, Windows 10,powershell 5.1.

**Comment by zag2me** [comment]
Windows 2008 so back to Vista days sorry! 

Powershell 3.0

I'm guessing it can't do that.

**Comment by mmmmmtasty** [comment]
Can you add the following between line 11 and 12 and send me the output?

`$websession`
`return`

**Comment by zag2me** [comment]
Bah, no go unfortunately. This page seems to indicate 3.0 is the last Powershell version available for 2008 :(

http://social.technet.microsoft.com/wiki/contents/articles/21016.how-to-install-windows-powershell-4-0.aspx

I'm guessing the function was introduced in 4.0

**Comment by zag2me** [comment]
Should be moving to a new 2016 server soon so I will get this up and running as soon as possible ;)
