### ISSUE TITLE
Support subdirectories

### ISSUE THREAD

**Issue by Bart274** [mmmmmtasty/SportScanner#2]
Hi,
When I use my current structure my media isn't recognized so I need to change my structure.

Now I need to have:
Sports\Basketball\NBA - 2015.06.17 - Cleveland Cavaliers v Golden State Warriors.mkv

What I want however is the following structure:
Sports\Basketball\NBA\Season 1415\NBA - 2015.06.17 - Cleveland Cavaliers v Golden State Warriors.mkv

This way I can easily separate my different sports and I can separate my different seasons.

**Comment by Bart274** [comment]
For me, the name of the episode wouldn't need to be build using the subdirectories, they could still use just the file name, but they should simply need to support subdirectories

**Comment by mmmmmtasty** [comment]
Agreed, this was in the plans from the beginning, I'll start work on it now.

**Comment by mmmmmtasty** [comment]
This has been done and committed. Let me know if you have any issues. Like you mentioned, the name of the event, the date and the league all still need to be in the file name.
