### ISSUE TITLE
Feature Request: Multipart Files

### ISSUE THREAD

**Issue by alberto467** [mmmmmtasty/SportScanner#20]
To organize my Formula 1 media, multipart files are a must. For each race i have a `pre-quali`, `quali`, `post-quali`, `teds notebook`, `pre-race`, `race` and `post-race` file, that must be combined in a single episode to match a single race.
To do this, the best option are multipart files, not the optimal option, but the best we have. With the current SportScanner, i have 7 episode for each race, only 2 get matched and the titles of the rest are from the filenames, which are fine, but the problem is having 7 times the episodes.
I tried researching a bit but all of the other scanner i found don't support multipart files either, is it even possible to support them with a custom scanner or is it just a bit complicated?

**Comment by alberto467** [comment]
The files are picked up correctly, but for some weird reason when i try to play the episode it just says `impossible to reproduce`.
![immagine](https://cloud.githubusercontent.com/assets/14240445/21111114/498a941c-c0a0-11e6-82c2-bdfb58546894.png)

**Comment by zag2me** [comment]
My intention is to add the seperate parts of motorsport events so its supported in the future. Not yet though as there are a few things to fix first on TheSportsDB.

**Comment by mmmmmtasty** [comment]
Sorry, I have no intention of adding support for this. I am more than willing to review PRs if anyone else wants to take it on

**Comment by nicmcr** [comment]
@alberto467 did you solve the F1 scanning?

**Comment by mmmmmtasty** [comment]
As stated previously I will not be implementing this
