### ISSUE TITLE
Powershell scripts

### ISSUE THREAD

**Issue by zag2me** [mmmmmtasty/SportScanner#21]
Hey the new TSDB server and site are up and I have just tested the import scripts successfully.

@mmmmmtasty can you check from your end if they are working OK?

I get a CSV file but both basketball and NHL are missing a few random teams. I've checked and they exist on TSDB. I've tested with the new 1617 season and a 2016 start date.

I'm wondering if they just changed names or something on the API.

Example San antonio spurs, utah jazz, raptors and timberwolves seem to be missing for NBA.

Same thing on NHL, few teams missing.

**Comment by zag2me** [comment]
Never mind, found an issue with the API where it was limiting to 26 teams in the NHL where there are now 30 for the new 2016/2017 season. Fully working again now ;)

I'll submit a PR for updating the season and dates at some point.

Thanks again!

**Comment by mmmmmtasty** [comment]
Please do, apologies I no longer maintain this project, hence the slow (or complete lack of) responses. I will still happily deal with any PRs though and take a look at things if I have time. Send it over!
