### ISSUE TITLE
API Key disabled

### ISSUE THREAD

**Issue by jbalcorn** [mmmmmtasty/SportScanner#35]
The API key was apparently taken off the github and was being used to hammer the site, so it was disabled.   So SS won't work now unless you sign up for your own API key.

website moderator told me:
"Yes sportscanner api key was disabled, I think it was leaked. It was being used constantly and slowing down the site.

You can use the new one as a drop in replacement.

I’m happy for someone to re add it to GitHub as well as long as it’s encrypted in some way.
"

I submitted a pull request to allow anyone to use their own key, but we need to figure out a way to have a default key that is encrypted (or at least encoded) in some way.   I'll do a little research on how best to do that.

**Comment by jbalcorn** [comment]
I'm in conversation with the site owner.  We're working on some kind of solution.

**Comment by zag2me** [comment]
Yep just confirming this, we are working on a solution. Thanks for taking this up, i'd love to see sportscanner users working and active on our site as well adding events.

**Comment by mmmmmtasty** [comment]
Btw zag, feel free to link to this project from the site if you haven't
already, as you can see, I'm not developing it but I am still reviewing the
PRs
