### ISSUE TITLE
plex keeps adding the same event multiple times each day

### ISSUE THREAD

**Issue by Bart274** [mmmmmtasty/SportScanner#4]
Hi,
If I add a new event, then I get a message that Plex has added a new episode.
When I add another new event on the same day (even if the events have different days) then I get 2 messages of new episodes: one from the first episode and one for the second episode.
When I add a third event, I get 3 messages...
Is this a problem from your scanner?

**Comment by mmmmmtasty** [comment]
What are you using to get the notifications?

So you are saying that if, on a single day, you add an event for
2015-10-03, one for 2015-10-06 and one fore 2015-10-09 for example you will
get three notifications when the third one is added?

And adding an event the next day will only send you one notification?

**Comment by Bart274** [comment]
I use Plexwatch for my notifications: https://github.com/ljunkie/plexWatch

It's exactly as you described:
I add the event of 2015-10-03 and get one notification for that event
Later that day I add the event of 2015-10-06 and I get two notifications, so I get the first one 2 times
On the end of that day I add the event of 2015-10-09 and I get 3 notifications.
At the beginning of the next day I add the event of 2015-10-12 and I only get one notification.

I don't have this problem with other series or with movies, only with my Sports section

**Comment by Bart274** [comment]
hmm, I just added a new event and looked at my notifications:
I have got a notification for each event I added since yesterday.
I'll try rebooting my pc and see if I still have that issue ;)

**Comment by mmmmmtasty** [comment]
This was due to the fact that epiosde numbers would be different every time you scanned a file. I've changed it to use a hash of the filename rather than a random number and it looks good now.

**Comment by Bart274** [comment]
great! thanks! :)
