### ISSUE TITLE
Feature request: More detail in episode.summary

### ISSUE THREAD

**Issue by rickjtaylor** [mmmmmtasty/SportScanner#9]
Today, the episode.summary is being set to "Matched by SportScanner"

I've now taken to updating that manually with more descriptive info, the following:
episode.summary = matched_episode['strAwayTeam']+" ("+matched_episode['intAwayScore']+") at "+matched_episode['strHomeTeam']+" ("+matched_episode['intHomeScore']+")\r\n\r\n"+matched_episode['strDescriptionEN']+"\r\n\r\nMatched by SportScanner"

For NBA games, it ends up very nice looking in Plex.

Consider adding some more detail to the summary field. It seems to be the primary "custom" field in Plex where one could add more detail from thesportsdb.com

I recognize that my format is only appropriate for sports where there are two competing teams. I suspect a more elegant, "sport-aware" solution exists.

Thanks!

p.s. I don't know why, the \r\n do nothing. They did in a previous version of the agent. One thing at a time :)

**Comment by mmmmmtasty** [comment]
I like the idea and I think I can put some effort into making it nice (maybe including stadium/track names where relevant as well).

I really DONT like the idea of putting the score in the description though! If I go to watch a game that happened the previous evening I really really really don't want to see the score before I watch it.

I'll put this on the stack though, watch this space.

**Comment by Bart274** [comment]
Yeah, I also like that idea, but indeed without the score. That would be a huge spoiler :)

**Comment by rickjtaylor** [comment]
Agreed! Score is dumb idea. My bad!

**Comment by mmmmmtasty** [comment]
I've added some stuff that should be able to help for sports where there are two teams competing or motorsports. More stuff will be added but let me know what you think

**Comment by rickjtaylor** [comment]
I am very happy with how this is, right now. Works perfectly for the things that I have been scanning. Can't wait to see new stuff. Thanks!

**Comment by mmmmmtasty** [comment]
I have no plans to change anything here so I'm closing this. New feature requests please if anyone wants anything different.
